//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xBitz.EasyXLR.TestRepo.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IXlReportService")]
    public interface IXlReportService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXlReportService/GetReport", ReplyAction="http://tempuri.org/IXlReportService/GetReportResponse")]
        xBitz.EasyXLR.Model.ReportData GetReport();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IXlReportService/GetReport", ReplyAction="http://tempuri.org/IXlReportService/GetReportResponse")]
        System.Threading.Tasks.Task<xBitz.EasyXLR.Model.ReportData> GetReportAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IXlReportServiceChannel : xBitz.EasyXLR.TestRepo.ServiceReference1.IXlReportService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class XlReportServiceClient : System.ServiceModel.ClientBase<xBitz.EasyXLR.TestRepo.ServiceReference1.IXlReportService>, xBitz.EasyXLR.TestRepo.ServiceReference1.IXlReportService {
        
        public XlReportServiceClient() {
        }
        
        public XlReportServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public XlReportServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XlReportServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XlReportServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public xBitz.EasyXLR.Model.ReportData GetReport() {
            return base.Channel.GetReport();
        }
        
        public System.Threading.Tasks.Task<xBitz.EasyXLR.Model.ReportData> GetReportAsync() {
            return base.Channel.GetReportAsync();
        }
    }
}
